CREATE TABLE IF NOT EXISTS USUARIOS (
id BIGINT NOT NULL AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL UNIQUE,
email VARCHAR(100) NOT NULL UNIQUE,
senha VARCHAR(300) NOT NULL,
ativo TINYINT NOT NULL,
PRIMARY KEY (id)
);




