INSERT INTO USUARIOS (NOME, EMAIL, SENHA, ATIVO) VALUES ('MANUEL.ESTEVEZ', 'manue.estevez@aluara.com', '$2a$10$2vA3kR.GOyGyjOyFNDWpf.tvcAgwQoxVFkq5Pq.jq.gSHVRC6zF7.', TRUE);
INSERT INTO USUARIOS (NOME, EMAIL, SENHA, ATIVO) VALUES ('ILKAY.GUNDOGAN', 'ilkay.gundogan@aluara.com', '1234', TRUE);
INSERT INTO USUARIOS (NOME, EMAIL, SENHA, ATIVO) VALUES ('KEVIN.DEBRUYNE', 'kevin.debruyne@aluara.com', '1234', TRUE);
INSERT INTO USUARIOS (NOME, EMAIL, SENHA, ATIVO) VALUES ('MANUEL.AKANYI', 'manuel.akanyi@aluara.com', '1234', TRUE);
INSERT INTO USUARIOS (NOME, EMAIL, SENHA, ATIVO) VALUES ('EDERNSON.MORAES', 'edernon.moraes@aluara.com', '1234', TRUE);

INSERT INTO CURSOS (NOME, CATEGORIA) VALUES ('SQL','BASE DE DADOS');
INSERT INTO CURSOS (NOME, CATEGORIA) VALUES ('JAVA','PROGRAMAÇÃO');
INSERT INTO CURSOS (NOME, CATEGORIA) VALUES ('PYTHON','PROGRAMAÇÃO');
INSERT INTO CURSOS (NOME, CATEGORIA) VALUES ('SPRING BOOT','FRAMEWORK');
INSERT INTO CURSOS (NOME, CATEGORIA) VALUES ('HTML','WEB');

INSERT INTO TOPICOS (TITULO, MENSAGEM, DATA_CRIACAO, STATUS, ID_USUARIO, ID_CURSO) VALUES ('PROBLEMAS COM SQL', 'NÃO POSSO CRIAR UMA CHAVE ESTRANGEIRA', '2024-12-16', 'NÃO_RESPONDIDO', 1, 1);
INSERT INTO TOPICOS (TITULO, MENSAGEM, DATA_CRIACAO, STATUS, ID_USUARIO, ID_CURSO) VALUES ('PROBLEMAS COM JAVA', 'NÃO POSSO USAR ENUM', '2024-12-16', 'NÃO_RESPONDIDO', 2, 2);
INSERT INTO TOPICOS (TITULO, MENSAGEM, DATA_CRIACAO, STATUS, ID_USUARIO, ID_CURSO) VALUES ('PROBLEMAS COM PYTHON', 'NÃO POSSO CRIAR UMA LISTA', '2024-12-16', 'NÃO_RESPONDIDO', 3, 3);
INSERT INTO TOPICOS (TITULO, MENSAGEM, DATA_CRIACAO, STATUS, ID_USUARIO, ID_CURSO) VALUES ('PROBLEMAS COM SPRING BOOT', 'NÃO POSSO USAR JPA', '2024-12-16', 'NÃO_RESPONDIDO', 4, 4);
INSERT INTO TOPICOS (TITULO, MENSAGEM, DATA_CRIACAO, STATUS, ID_USUARIO, ID_CURSO) VALUES ('PROBLEMAS COM HTML', 'NÃO POSSO CRIAR UM DIV', '2024-12-16', 'NÃO_RESPONDIDO', 5, 5);
